### ISSUE TITLE
undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by hpcprofessional** [puppetlabs/prosvc-preview_report#3]
Working with some non-public data that was created by the catalog_preview module, I'm getting this error. I can provide the non-public data to a Puppet person or, if necessary, I can spend awhile sanitizing the data for public consumption. Let me know.

```
# /somewhere/prosvc-preview_report/preview_report.rb -f /somewhere/catalog_preview.json -w /somewhere/catalog_preview.html

/etc/puppetlabs/puppet/modules/prosvc-preview_report/preview_report.rb:520:in `block (2 levels) in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/markaby-0.8.0/lib/markaby/builder.rb:162:in `instance_eval'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/markaby-0.8.0/lib/markaby/builder.rb:162:in `capture'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/markaby-0.8.0/lib/markaby/builder.rb:207:in `tag!'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/markaby-0.8.0/lib/markaby/builder_tags.rb:23:in `html_tag'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/markaby-0.8.0/lib/markaby/builder_tags.rb:9:in `body'
    from /etc/puppetlabs/puppet/modules/prosvc-preview_report/preview_report.rb:442:in `block in <main>'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/markaby-0.8.0/lib/markaby/builder.rb:162:in `instance_eval'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/markaby-0.8.0/lib/markaby/builder.rb:162:in `capture'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/markaby-0.8.0/lib/markaby/builder.rb:207:in `tag!'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/markaby-0.8.0/lib/markaby/builder_tags.rb:23:in `html_tag'
    from /opt/puppet/lib/ruby/gems/1.9.1/gems/markaby-0.8.0/lib/markaby/builder_tags.rb:9:in `html'
    from /etc/puppetlabs/puppet/modules/prosvc-preview_report/preview_report.rb:73:in `<main>'
```

**Comment by acidprime** [comment]
@hpcprofessional should be resolved with a8724cb61ea929c2a36cd4eba3ab766ea4fc3294, let me know and I will cut a bug release tag

**Comment by hpcprofessional** [comment]
Yes. The fix works for the test case. Thanks!

**Comment by vchepkov** [comment]
This problem is back after upgrade to PE2017.3.4

```
/opt/preview_report/preview_report.rb:561:in `block (2 levels) in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/markaby-0.9.0/lib/markaby/builder.rb:142:in `instance_eval'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/markaby-0.9.0/lib/markaby/builder.rb:142:in `capture'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/markaby-0.9.0/lib/markaby/builder.rb:193:in `tag!'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/markaby-0.9.0/lib/markaby/builder_tags.rb:23:in `html_tag'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/markaby-0.9.0/lib/markaby/builder_tags.rb:5:in `body'
	from /opt/preview_report/preview_report.rb:436:in `block in <main>'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/markaby-0.9.0/lib/markaby/builder.rb:142:in `instance_eval'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/markaby-0.9.0/lib/markaby/builder.rb:142:in `capture'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/markaby-0.9.0/lib/markaby/builder.rb:193:in `tag!'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/markaby-0.9.0/lib/markaby/builder_tags.rb:23:in `html_tag'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/markaby-0.9.0/lib/markaby/builder_tags.rb:5:in `html'
	from /opt/preview_report/preview_report.rb:74:in `<main>'
```
